// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQogL1bsohkK5_181j1mwLWmyF7oXaB1I',
    appId: '1:858691323471:web:ec536babd6641eefa8cc3a',
    messagingSenderId: '858691323471',
    projectId: 'financial-b7b5b',
    authDomain: 'financial-b7b5b.firebaseapp.com',
    storageBucket: 'financial-b7b5b.firebasestorage.app',
    measurementId: 'G-5FHSZ3DJ3H',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWm1mOIXu2q5HlK3JzZ7WMa_n57XhWawc',
    appId: '1:858691323471:ios:2f83fa1fac62ad24a8cc3a',
    messagingSenderId: '858691323471',
    projectId: 'financial-b7b5b',
    storageBucket: 'financial-b7b5b.firebasestorage.app',
    iosBundleId: 'com.example.financial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWm1mOIXu2q5HlK3JzZ7WMa_n57XhWawc',
    appId: '1:858691323471:ios:2f83fa1fac62ad24a8cc3a',
    messagingSenderId: '858691323471',
    projectId: 'financial-b7b5b',
    storageBucket: 'financial-b7b5b.firebasestorage.app',
    iosBundleId: 'com.example.financial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQogL1bsohkK5_181j1mwLWmyF7oXaB1I',
    appId: '1:858691323471:web:0968e8e54481b055a8cc3a',
    messagingSenderId: '858691323471',
    projectId: 'financial-b7b5b',
    authDomain: 'financial-b7b5b.firebaseapp.com',
    storageBucket: 'financial-b7b5b.firebasestorage.app',
    measurementId: 'G-5GF7NDBMRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAeL_L4OTUTowPXlHmXypg0daxkaMrV1A',
    appId: '1:858691323471:android:8a8afd85a2176aeaa8cc3a',
    messagingSenderId: '858691323471',
    projectId: 'financial-b7b5b',
    storageBucket: 'financial-b7b5b.firebasestorage.app',
  );

}